namespace Nebula.Proxying;

/// <summary>
/// All members marked with this attribute is generated by the proxy generator.
/// </summary>
[AttributeUsage(AttributeTargets.All)]
public class GeneratedAttribute : Attribute
{}