namespace Nebula.Prism;

/// <summary>
/// Anything marked with this means that it is generated by prism.
/// </summary>
[AttributeUsage(validOn: AttributeTargets.All)]
public class GeneratedByPrismAttribute : Attribute
{
    private readonly object? AdditionalData;

    public GeneratedByPrismAttribute()
    {
        AdditionalData = null;
    }

    public GeneratedByPrismAttribute(object data)
    {
        AdditionalData = data;
    }
}