name: Publish Packages

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
  pull_request:
    tags: 
      - v[0-9].[0-9]+.[0-9]+
  release:
    types: [published]

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: | 
        dotnet restore
        dotnet build -c Release --no-restore
        dotnet pack --configuration Release -o Packages/Release
    - name: Publish
      run: |
        dotnet nuget add source --username Pygmalions --password ${{ secrets.ACTION_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Pygmalions/index.json"
        dotnet nuget push "Packages/Release/*.nupkg" --api-key ${{ secrets.ACTION_PAT }} --source "github" --skip-duplicate
        dotnet nuget push "Packages/Release/*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
