name: Publish Packages

on:
  push:
    branches: [ main ]
    tags: v**
  pull_request:
    branches: [ main ]
    tags: v**

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release -o Packages/Release
    - name: Add Github Source
      run: 
        dotnet nuget add source --username NebulaCommittee --password ${{ secrets.ACTION_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NebulaCommittee/index.json"
    - name: Publish
      run:
        dotnet nuget push "Packages/Release/*.nupkg" --api-key ${{ secrets.ACTION_PAT }} --source "github" --skip-duplicate
